In [11]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

#LabelEncoder를 객채로 생성한후 fit 과 transform 으로 레이블 인코딩 실행 

encoder=LabelEncoder()
encoder.fit(items)

labels=encoder.transform(items)
labels
print('인코딩 변환값:',labels)

print('인코딩 클래스:',encoder.classes_)
print('디코딩 원본값:',encoder.inverse_transform([4,5,0,1,1,3,3]))

인코딩 변환값: [0 1 4 5 3 3 2 2]
인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']
디코딩 원본값: ['전자레인지' '컴퓨터' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']

원-핫 인코딩 같은경우 머신러닝에서 숫자 값에 따른 순서나 중요도로 인식하지 않게 하는것

In [21]:
from sklearn.preprocessing import OneHotEncoder 
import numpy as np 
import pandas as pd

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)

#2차원 데이터로 변경
labels=labels.reshape(-1,1)
labels

#원-핫 인코딩 이용 

oh_encoder=OneHotEncoder()
oh_encoder.fit(labels)
oh_labels=oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

#pd.get_dummies(DataFrame)이용 더미변수 생성이 더 빠름

df=pd.DataFrame({'items':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)

   items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0

In [ ]:
#피쳐 스케일링 정규화 대표적으로 표준화와 정규화가 존재

from sklearn.datasets import load_iris
import pandas as pd 

#iris data frame

iris=load_iris()
iris_data=iris.data
iris_df=pd.DataFrame(data=iris_data,columns=iris.feature_names)
iris_df

In [25]:
print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [35]:
from sklearn.preprocessing import StandardScaler 

#StandardScaler 객체 생성
scaler=StandardScaler()
#fit과 transform 호출
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)
iris_scaled
#transform()시 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame 으로 변호나

iris_df_scaled=pd.DataFrame(data=iris_scaled,columns=iris.feature_names)
iris_df_scaled

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
..                 ...               ...                ...               ...
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler

#MinMaxScaler 객체생성 

scaler=MinMaxScaler()
sclaer.fit(iris_df)